### ISSUE TITLE
don't want public ip 

### ISSUE THREAD

**Issue by hehehehe123** [terraform-alicloud-modules/terraform-alicloud-ecs-instance#17]
hi, I had already use this module, but it automatic create an public ip address. I don't need the public ip address.  Could you tell me how to do that.

**Comment by xiaozhu36** [comment]
HI @hehehehe123 Thanks for your usage. You can close public ip by setting `internet_max_bandwidth_out ` to 0.

**Comment by hehehehe123** [comment]
Hi @xiaozhu36  Thanks a lot.
